//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class danhmuc
    {
        public int id { get; set; }
        public string loaiSanPham { get; set; }
        public string tenhangsx { get; set; }

        public virtual ICollection<sanpham> sanphams { get; set; }
    }
}
