//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class donhang
    {
        public int id { get; set; }
        public khachhang khachhang { get; set; }
        public Nullable<System.DateTime> ngaygiaodich { get; set; }
        public Nullable<System.DateTime> ngaygiaohang { get; set; }
        public Nullable<double> giatridon { get; set; }
    }
}
