//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class donhang
    {
        //[Key]
        public int id { get; set; }
        public int khachhangid { get; set; }
        //[ForeignKey("khachhangid")]
        public virtual khachhang khachhang { get; set; }
        public Nullable<System.DateTime> ngaygiaodich { get; set; }
        public Nullable<System.DateTime> ngaygiaohang { get; set; }
        public string diachigiaohang { get; set; }
        public string sdtlienlac { get; set; }
        public string emailLienLac { get; set; }
        public string trangthai { get; set; }
        public Nullable<double> giatridon { get; set; }
        public virtual ICollection<chitietdonhang> Chitietdonhang { get; set; }
    }
}
