//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models.DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class khuyenmai
    {
        [Key]
        public int idKhuyenMai { get; set; }
        public string noidungKhuyenMai { get; set; }
        public Nullable<double> phanTramGiamGia { get; set; }
        public sanpham sanpham { get; set; }
 
    }
}
