//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class phukien
    {
        public int idPhuKien { get; set; }
        public Nullable<int> idkhuyenmai { get; set; }
        public Nullable<int> iddanhMuc { get; set; }
        public string moTa { get; set; }
        public Nullable<double> giaTien { get; set; }
        public string hinhanhsanPham { get; set; }
    }
}
