//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models.DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class resourcetable
    {
        [Key]
        public int idresourceTable { get; set; }
        public roletable roletable { get; set; }
        public string controller { get; set; }
        public string action { get; set; }
    }
}
