//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Models.DAO
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class thongso
    {
        [Key]
        public int id { get; set; }
        public string hedieuhanh { get; set; }
        public string loaimanhinh { get; set; }
        public string dophangiai { get; set; }
        public string manhinhrong { get; set; }
        public string camerasau { get; set; }
        public string cameratruoc { get; set; }
        public string quayphim { get; set; }
        public string tocdocpu { get; set; }
        public string chipset { get; set; }
        public string ram { get; set; }
        public string chipdohoa { get; set; }
        public string rom { get; set; }
        public string theNhoNgoai { get; set; }
        public string trongluong { get; set; }
        public string dungluongpin { get; set; }
        public string bluetooth { get; set; }
        public string wifi { get; set; }
        public string C5G { get; set; }
        public string loaisim { get; set; }
        public sanpham sanpham { get; set; }
    }
}
